name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.2', '3.3', '3.4', '4.0' ]
    name: Ruby ${{ matrix.ruby }} unit testing on ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler_cache: true
    - name: Run the default task
      run: |
        bundle install
        TZ=Asia/Tokyo TESTOPTS="--verbose" bundle exec rake
